db:
  image: postgres:9.5
  environment:
    - POSTGRES_PASSWORD=domino
    - POSTGRES_USER=domino
  expose:
    - "5432"
  ports:
    - "5432:5432"

as:
  build: ./app/
  volumes:
    - ./app:/usr/src/app
  working_dir: /usr/src/app
  environment:
    - PYTHONPATH=/usr/src/app
    - DJANGO_SETTINGS_MODULE=app.settings
  command: python manage.py runserver 0.0.0.0:8000
  ports:
    - "80:8000"
  links:
    - db:db
