version: '2'

services:
    db:
      image: postgres:9.6
      environment:
        - POSTGRES_PASSWORD=domino
        - POSTGRES_USER=domino
      expose:
        - "5432"
      ports:
        - "5432:5432"
      network_mode: bridge

    as:
      build: ./app/
      environment:
        - PYTHONPATH=/usr/src/app
        - DJANGO_SETTINGS_MODULE=app.settings
        - PYTHONUNBUFFERED=1
      volumes:
        - ./app:/usr/src/app
        - /var/run/docker.sock:/var/run/docker.sock
        - ~/.config/sublime-text-3/Packages/Anaconda:/opt/anaconda
      ports:
        - "80:8000"
        - "19360:19360" # for anaconda miniserver
      links:
        - db:db
      network_mode: bridge
      working_dir: /usr/src/app
      command: python manage.py runserver 0.0.0.0:8000
